### ISSUE TITLE
error: unexpected keyword argument 'verbose'

### ISSUE THREAD

**Issue by ghost** [DarwinAwardWinner/transfercoder#1]
Hi, when running transfercoder I get the following error :
```
ERROR: Exception while transcoding [...] run() got an unexpected keyword argument 'verbose'
```

I fixed the error by changing line 301 of `__init__.py` from this :
``` python
ff.run(verbose=False)
```
to this :
``` python
ff.run()
```

And it works fine (but it's really verbose).
By the way thank you for this tool !

**Comment by DarwinAwardWinner** [comment]
Hi. Thanks for the report. I'll look into it when I have time.

**Comment by DarwinAwardWinner** [comment]
I've fixed this and also set up transfercoder to only show ffmpeg output when in verbose mode.

**Comment by ghost** [comment]
Cool, thanks !
