### ISSUE TITLE
Transfercoder is leaking file descriptors

### ISSUE THREAD

**Issue by tfreedman** [DarwinAwardWinner/transfercoder#7]
Every file that gets transcoded has a file in /tmp/transfercoder_XXXXXX/ temporarily, which then gets deleted as it gets moved to the destination volume. Unfortunately, the descriptor is held open until transfercoder itself exits, which causes the /tmp/ volume to keep filling up until transfercoder either finishes or crashes due to a lack of disk space.

**Comment by DarwinAwardWinner** [comment]
Unfortunately, I've tried several times to fix this (most recently: https://github.com/DarwinAwardWinner/transfercoder/commit/91eed93e15eed40b08cdd6a693f491ef5f31ea9b) but apparently I have still been unsuccessful. Do you have any idea how to fix it? One think you can try is `-j 0` to take multiprocessing out of the picture. I'd be interested to know if it still leaks file descriptors then.

**Comment by tfreedman** [comment]
Should be fixed in the latest commit.
